services:
  - type: web
    name: MyFileKeeperBot
    env: python
    runtime: python3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_TOKEN
        value: "7008153713:AAFbvPB1l6sRfRop7J7X_yTKWuqJClnKs6M"
