services:
  - type: web
    name: tg-moderator-bot
    env: python
    startCommand: python tg_moderator_bot/bot.py
    buildCommand: pip install -r tg_moderator_bot/requirements.txt
    envVars:
      - key: BOT_TOKEN
        value: <твой_токен>
      - key: SUPERADMIN_ID
        value: "954426279"
